/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerificationRouteImport } from './routes/verification'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as TreasuryRouteImport } from './routes/treasury'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as RiskRouteImport } from './routes/risk'
import { Route as RegenerativeRouteImport } from './routes/regenerative'
import { Route as ReferralsRouteImport } from './routes/referrals'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OrchestratorRouteImport } from './routes/orchestrator'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as ObservabilityRouteImport } from './routes/observability'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as IdentityRouteImport } from './routes/identity'
import { Route as GrowthRouteImport } from './routes/growth'
import { Route as FundingRouteImport } from './routes/funding'
import { Route as EconomicGraphRouteImport } from './routes/economic-graph'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CfoRouteImport } from './routes/cfo'
import { Route as BusinessOsRouteImport } from './routes/business-os'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as EligibilityRouteImport } from './routes/eligibility'
import { Route as RevenueRouteImport } from './routes/revenue'
import { Route as CashflowRouteImport } from './routes/cashflow'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsNotificationsRouteImport } from './routes/settings.notifications'
import { Route as BillingCallbackRouteImport } from './routes/billing.callback'
import { Route as ApiVaultFileRouteImport } from './routes/api/vault-file'
import { Route as ApiSessionRouteImport } from './routes/api/session'
import { Route as ApiEmbedRouteImport } from './routes/api/embed'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiCfoToolsRouteImport } from './routes/api/cfo-tools'
import { Route as AnalyticsFundingRouteImport } from './routes/analytics.funding'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as ApiPublicPaystackWebhookRouteImport } from './routes/api/public/paystack-webhook'

const VerificationRoute = VerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const TreasuryRoute = TreasuryRouteImport.update({
  id: '/treasury',
  path: '/treasury',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskRoute = RiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const RegenerativeRoute = RegenerativeRouteImport.update({
  id: '/regenerative',
  path: '/regenerative',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsRoute = ReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OrchestratorRoute = OrchestratorRouteImport.update({
  id: '/orchestrator',
  path: '/orchestrator',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const ObservabilityRoute = ObservabilityRouteImport.update({
  id: '/observability',
  path: '/observability',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentityRoute = IdentityRouteImport.update({
  id: '/identity',
  path: '/identity',
  getParentRoute: () => rootRouteImport,
} as any)
const GrowthRoute = GrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => rootRouteImport,
} as any)
const FundingRoute = FundingRouteImport.update({
  id: '/funding',
  path: '/funding',
  getParentRoute: () => rootRouteImport,
} as any)
const EconomicGraphRoute = EconomicGraphRouteImport.update({
  id: '/economic-graph',
  path: '/economic-graph',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CfoRoute = CfoRouteImport.update({
  id: '/cfo',
  path: '/cfo',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessOsRoute = BusinessOsRouteImport.update({
  id: '/business-os',
  path: '/business-os',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const EligibilityRoute = EligibilityRouteImport.update({
  id: '/eligibility',
  path: '/eligibility',
  getParentRoute: () => rootRouteImport,
} as any)
const RevenueRoute = RevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const CashflowRoute = CashflowRouteImport.update({
  id: '/cashflow',
  path: '/cashflow',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/settings/notifications',
  path: '/settings/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingCallbackRoute = BillingCallbackRouteImport.update({
  id: '/billing/callback',
  path: '/billing/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVaultFileRoute = ApiVaultFileRouteImport.update({
  id: '/api/vault-file',
  path: '/api/vault-file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionRoute = ApiSessionRouteImport.update({
  id: '/api/session',
  path: '/api/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmbedRoute = ApiEmbedRouteImport.update({
  id: '/api/embed',
  path: '/api/embed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCfoToolsRoute = ApiCfoToolsRouteImport.update({
  id: '/api/cfo-tools',
  path: '/api/cfo-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsFundingRoute = AnalyticsFundingRouteImport.update({
  id: '/analytics/funding',
  path: '/analytics/funding',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaystackWebhookRoute =
  ApiPublicPaystackWebhookRouteImport.update({
    id: '/api/public/paystack-webhook',
    path: '/api/public/paystack-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/cashflow': typeof CashflowRoute
  '/revenue': typeof RevenueRoute
  '/eligibility': typeof EligibilityRoute
  '/audit': typeof AuditRoute
  '/business-os': typeof BusinessOsRoute
  '/cfo': typeof CfoRoute
  '/community': typeof CommunityRoute
  '/economic-graph': typeof EconomicGraphRoute
  '/funding': typeof FundingRoute
  '/growth': typeof GrowthRoute
  '/identity': typeof IdentityRoute
  '/impact': typeof ImpactRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/observability': typeof ObservabilityRoute
  '/opportunities': typeof OpportunitiesRoute
  '/orchestrator': typeof OrchestratorRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/referrals': typeof ReferralsRoute
  '/regenerative': typeof RegenerativeRoute
  '/risk': typeof RiskRoute
  '/subscription': typeof SubscriptionRoute
  '/treasury': typeof TreasuryRoute
  '/vault': typeof VaultRoute
  '/verification': typeof VerificationRoute
  '/admin/roles': typeof AdminRolesRoute
  '/analytics/funding': typeof AnalyticsFundingRoute
  '/api/cfo-tools': typeof ApiCfoToolsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/embed': typeof ApiEmbedRoute
  '/api/session': typeof ApiSessionRoute
  '/api/vault-file': typeof ApiVaultFileRoute
  '/billing/callback': typeof BillingCallbackRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/cashflow': typeof CashflowRoute
  '/revenue': typeof RevenueRoute
  '/eligibility': typeof EligibilityRoute
  '/audit': typeof AuditRoute
  '/business-os': typeof BusinessOsRoute
  '/cfo': typeof CfoRoute
  '/community': typeof CommunityRoute
  '/economic-graph': typeof EconomicGraphRoute
  '/funding': typeof FundingRoute
  '/growth': typeof GrowthRoute
  '/identity': typeof IdentityRoute
  '/impact': typeof ImpactRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/observability': typeof ObservabilityRoute
  '/opportunities': typeof OpportunitiesRoute
  '/orchestrator': typeof OrchestratorRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/referrals': typeof ReferralsRoute
  '/regenerative': typeof RegenerativeRoute
  '/risk': typeof RiskRoute
  '/subscription': typeof SubscriptionRoute
  '/treasury': typeof TreasuryRoute
  '/vault': typeof VaultRoute
  '/verification': typeof VerificationRoute
  '/admin/roles': typeof AdminRolesRoute
  '/analytics/funding': typeof AnalyticsFundingRoute
  '/api/cfo-tools': typeof ApiCfoToolsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/embed': typeof ApiEmbedRoute
  '/api/session': typeof ApiSessionRoute
  '/api/vault-file': typeof ApiVaultFileRoute
  '/billing/callback': typeof BillingCallbackRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/cashflow': typeof CashflowRoute
  '/revenue': typeof RevenueRoute
  '/eligibility': typeof EligibilityRoute
  '/audit': typeof AuditRoute
  '/business-os': typeof BusinessOsRoute
  '/cfo': typeof CfoRoute
  '/community': typeof CommunityRoute
  '/economic-graph': typeof EconomicGraphRoute
  '/funding': typeof FundingRoute
  '/growth': typeof GrowthRoute
  '/identity': typeof IdentityRoute
  '/impact': typeof ImpactRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/observability': typeof ObservabilityRoute
  '/opportunities': typeof OpportunitiesRoute
  '/orchestrator': typeof OrchestratorRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/referrals': typeof ReferralsRoute
  '/regenerative': typeof RegenerativeRoute
  '/risk': typeof RiskRoute
  '/subscription': typeof SubscriptionRoute
  '/treasury': typeof TreasuryRoute
  '/vault': typeof VaultRoute
  '/verification': typeof VerificationRoute
  '/admin/roles': typeof AdminRolesRoute
  '/analytics/funding': typeof AnalyticsFundingRoute
  '/api/cfo-tools': typeof ApiCfoToolsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/embed': typeof ApiEmbedRoute
  '/api/session': typeof ApiSessionRoute
  '/api/vault-file': typeof ApiVaultFileRoute
  '/billing/callback': typeof BillingCallbackRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approvals'
    | '/cashflow'
    | '/revenue'
    | '/eligibility'
    | '/audit'
    | '/business-os'
    | '/cfo'
    | '/community'
    | '/economic-graph'
    | '/funding'
    | '/growth'
    | '/identity'
    | '/impact'
    | '/login'
    | '/notifications'
    | '/observability'
    | '/opportunities'
    | '/orchestrator'
    | '/pricing'
    | '/profile'
    | '/referrals'
    | '/regenerative'
    | '/risk'
    | '/subscription'
    | '/treasury'
    | '/vault'
    | '/verification'
    | '/admin/roles'
    | '/analytics/funding'
    | '/api/cfo-tools'
    | '/api/chat'
    | '/api/embed'
    | '/api/session'
    | '/api/vault-file'
    | '/billing/callback'
    | '/settings/notifications'
    | '/api/public/paystack-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approvals'
    | '/cashflow'
    | '/revenue'
    | '/eligibility'
    | '/audit'
    | '/business-os'
    | '/cfo'
    | '/community'
    | '/economic-graph'
    | '/funding'
    | '/growth'
    | '/identity'
    | '/impact'
    | '/login'
    | '/notifications'
    | '/observability'
    | '/opportunities'
    | '/orchestrator'
    | '/pricing'
    | '/profile'
    | '/referrals'
    | '/regenerative'
    | '/risk'
    | '/subscription'
    | '/treasury'
    | '/vault'
    | '/verification'
    | '/admin/roles'
    | '/analytics/funding'
    | '/api/cfo-tools'
    | '/api/chat'
    | '/api/embed'
    | '/api/session'
    | '/api/vault-file'
    | '/billing/callback'
    | '/settings/notifications'
    | '/api/public/paystack-webhook'
  id:
    | '__root__'
    | '/'
    | '/approvals'
    | '/cashflow'
    | '/revenue'
    | '/eligibility'
    | '/audit'
    | '/business-os'
    | '/cfo'
    | '/community'
    | '/economic-graph'
    | '/funding'
    | '/growth'
    | '/identity'
    | '/impact'
    | '/login'
    | '/notifications'
    | '/observability'
    | '/opportunities'
    | '/orchestrator'
    | '/pricing'
    | '/profile'
    | '/referrals'
    | '/regenerative'
    | '/risk'
    | '/subscription'
    | '/treasury'
    | '/vault'
    | '/verification'
    | '/admin/roles'
    | '/analytics/funding'
    | '/api/cfo-tools'
    | '/api/chat'
    | '/api/embed'
    | '/api/session'
    | '/api/vault-file'
    | '/billing/callback'
    | '/settings/notifications'
    | '/api/public/paystack-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApprovalsRoute: typeof ApprovalsRoute
  CashflowRoute: typeof CashflowRoute
  RevenueRoute: typeof RevenueRoute
  EligibilityRoute: typeof EligibilityRoute
  AuditRoute: typeof AuditRoute
  BusinessOsRoute: typeof BusinessOsRoute
  CfoRoute: typeof CfoRoute
  CommunityRoute: typeof CommunityRoute
  EconomicGraphRoute: typeof EconomicGraphRoute
  FundingRoute: typeof FundingRoute
  GrowthRoute: typeof GrowthRoute
  IdentityRoute: typeof IdentityRoute
  ImpactRoute: typeof ImpactRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  ObservabilityRoute: typeof ObservabilityRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  OrchestratorRoute: typeof OrchestratorRoute
  PricingRoute: typeof PricingRoute
  ProfileRoute: typeof ProfileRoute
  ReferralsRoute: typeof ReferralsRoute
  RegenerativeRoute: typeof RegenerativeRoute
  RiskRoute: typeof RiskRoute
  SubscriptionRoute: typeof SubscriptionRoute
  TreasuryRoute: typeof TreasuryRoute
  VaultRoute: typeof VaultRoute
  VerificationRoute: typeof VerificationRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AnalyticsFundingRoute: typeof AnalyticsFundingRoute
  ApiCfoToolsRoute: typeof ApiCfoToolsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiEmbedRoute: typeof ApiEmbedRoute
  ApiSessionRoute: typeof ApiSessionRoute
  ApiVaultFileRoute: typeof ApiVaultFileRoute
  BillingCallbackRoute: typeof BillingCallbackRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  ApiPublicPaystackWebhookRoute: typeof ApiPublicPaystackWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verification': {
      id: '/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof VerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treasury': {
      id: '/treasury'
      path: '/treasury'
      fullPath: '/treasury'
      preLoaderRoute: typeof TreasuryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk': {
      id: '/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof RiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regenerative': {
      id: '/regenerative'
      path: '/regenerative'
      fullPath: '/regenerative'
      preLoaderRoute: typeof RegenerativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals': {
      id: '/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof ReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orchestrator': {
      id: '/orchestrator'
      path: '/orchestrator'
      fullPath: '/orchestrator'
      preLoaderRoute: typeof OrchestratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observability': {
      id: '/observability'
      path: '/observability'
      fullPath: '/observability'
      preLoaderRoute: typeof ObservabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identity': {
      id: '/identity'
      path: '/identity'
      fullPath: '/identity'
      preLoaderRoute: typeof IdentityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/growth': {
      id: '/growth'
      path: '/growth'
      fullPath: '/growth'
      preLoaderRoute: typeof GrowthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funding': {
      id: '/funding'
      path: '/funding'
      fullPath: '/funding'
      preLoaderRoute: typeof FundingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/economic-graph': {
      id: '/economic-graph'
      path: '/economic-graph'
      fullPath: '/economic-graph'
      preLoaderRoute: typeof EconomicGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cfo': {
      id: '/cfo'
      path: '/cfo'
      fullPath: '/cfo'
      preLoaderRoute: typeof CfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-os': {
      id: '/business-os'
      path: '/business-os'
      fullPath: '/business-os'
      preLoaderRoute: typeof BusinessOsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cashflow': {
      id: '/cashflow'
      path: '/cashflow'
      fullPath: '/cashflow'
      preLoaderRoute: typeof CashflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revenue': {
      id: '/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof RevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eligibility': {
      id: '/eligibility'
      path: '/eligibility'
      fullPath: '/eligibility'
      preLoaderRoute: typeof EligibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/callback': {
      id: '/billing/callback'
      path: '/billing/callback'
      fullPath: '/billing/callback'
      preLoaderRoute: typeof BillingCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vault-file': {
      id: '/api/vault-file'
      path: '/api/vault-file'
      fullPath: '/api/vault-file'
      preLoaderRoute: typeof ApiVaultFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/session': {
      id: '/api/session'
      path: '/api/session'
      fullPath: '/api/session'
      preLoaderRoute: typeof ApiSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/embed': {
      id: '/api/embed'
      path: '/api/embed'
      fullPath: '/api/embed'
      preLoaderRoute: typeof ApiEmbedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cfo-tools': {
      id: '/api/cfo-tools'
      path: '/api/cfo-tools'
      fullPath: '/api/cfo-tools'
      preLoaderRoute: typeof ApiCfoToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/funding': {
      id: '/analytics/funding'
      path: '/analytics/funding'
      fullPath: '/analytics/funding'
      preLoaderRoute: typeof AnalyticsFundingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paystack-webhook': {
      id: '/api/public/paystack-webhook'
      path: '/api/public/paystack-webhook'
      fullPath: '/api/public/paystack-webhook'
      preLoaderRoute: typeof ApiPublicPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApprovalsRoute: ApprovalsRoute,
  CashflowRoute: CashflowRoute,
  RevenueRoute: RevenueRoute,
  EligibilityRoute: EligibilityRoute,
  AuditRoute: AuditRoute,
  BusinessOsRoute: BusinessOsRoute,
  CfoRoute: CfoRoute,
  CommunityRoute: CommunityRoute,
  EconomicGraphRoute: EconomicGraphRoute,
  FundingRoute: FundingRoute,
  GrowthRoute: GrowthRoute,
  IdentityRoute: IdentityRoute,
  ImpactRoute: ImpactRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  ObservabilityRoute: ObservabilityRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  OrchestratorRoute: OrchestratorRoute,
  PricingRoute: PricingRoute,
  ProfileRoute: ProfileRoute,
  ReferralsRoute: ReferralsRoute,
  RegenerativeRoute: RegenerativeRoute,
  RiskRoute: RiskRoute,
  SubscriptionRoute: SubscriptionRoute,
  TreasuryRoute: TreasuryRoute,
  VaultRoute: VaultRoute,
  VerificationRoute: VerificationRoute,
  AdminRolesRoute: AdminRolesRoute,
  AnalyticsFundingRoute: AnalyticsFundingRoute,
  ApiCfoToolsRoute: ApiCfoToolsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiEmbedRoute: ApiEmbedRoute,
  ApiSessionRoute: ApiSessionRoute,
  ApiVaultFileRoute: ApiVaultFileRoute,
  BillingCallbackRoute: BillingCallbackRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  ApiPublicPaystackWebhookRoute: ApiPublicPaystackWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
